import React from 'react';

export default function SummaryCard({ summary, loading }) {
    if (loading) {
        return (
            <div className="bg-white p-8 rounded-lg shadow-sm border border-gray-100 mb-12 animate-pulse">
                <div className="h-6 bg-gray-200 rounded w-1/3 mb-4"></div>
                <div className="space-y-3">
                    <div className="h-4 bg-gray-200 rounded w-full"></div>
                    <div className="h-4 bg-gray-200 rounded w-5/6"></div>
                    <div className="h-4 bg-gray-200 rounded w-4/6"></div>
                </div>
            </div>
        );
    }

    if (!summary) return null;

    return (
        <div className="bg-white p-8 rounded-lg shadow-sm border border-gray-100 mb-12 transform transition-all hover:translate-y-[-2px] hover:shadow-md duration-300">
            <div className="flex items-center justify-between mb-6">
                <h2 className="text-xl font-serif font-semibold text-text-main">
                    AI Overview
                </h2>
                <span className="text-xs font-sans text-gray-400 uppercase tracking-wider">
                    Testing Phase - Generated by Llama 3.1
                </span>
            </div>

            <div className="prose prose-stone max-w-none text-gray-600 font-sans leading-relaxed">
                {summary.summary ? (
                    summary.summary.split('\n').map((para, i) => (
                        para.trim() && <p key={i} className="mb-4">{para}</p>
                    ))
                ) : (
                    <p className="italic text-gray-400">No summary generated for this timeframe yet. Run the backend summarizer script.</p>
                )}
            </div>

            {summary.article_count > 0 && (
                <div className="mt-6 pt-6 border-t border-gray-100 text-sm text-gray-400 flex justify-between">
                    <span>Based on {summary.article_count} articles</span>
                    <span>{new Date(summary.generated_at).toLocaleDateString()}</span>
                </div>
            )}
        </div>
    );
}
