import { useState, useEffect } from 'react';
import TimeframeSelector from './components/TimeframeSelector';
import SummaryCard from './components/SummaryCard';
import ArticleStream from './components/ArticleStream';
import ReactMarkdown from 'react-markdown';

function App() {
  const [activeTab, setActiveTab] = useState('7d');
  const [allData, setAllData] = useState(null);
  const [articles, setArticles] = useState([]);
  const [trendSummary, setTrendSummary] = useState(null);
  const [loading, setLoading] = useState(true);
  const [selectedTrend, setSelectedTrend] = useState(null);

  // Pagination State
  const [page, setPage] = useState(1);
  const [hasMore, setHasMore] = useState(true);
  const [isFetchingMore, setIsFetchingMore] = useState(false);

  // 1. Initial Load of Static Data
  useEffect(() => {
    async function loadData() {
      try {
        setLoading(true);
        // Fetch the static snapshot generated by the update script
        const response = await fetch('./data.json');
        if (response.ok) {
          const data = await response.json();
          setAllData(data);
        } else {
          console.error("Failed to load data.json", response.statusText);
        }
      } catch (error) {
        console.error("Error loading static data:", error);
      } finally {
        setLoading(false);
      }
    }
    loadData();
  }, []);

  // 2. Reset on tab change
  useEffect(() => {
    setArticles([]);
    setPage(1);
    setHasMore(true);
    setTrendSummary(null);
    setSelectedTrend(null);
  }, [activeTab]);

  // 3. Filtering and Pagination (Client-side)
  useEffect(() => {
    if (!allData) return;

    function filterAndPaginate() {
      // Don't fetch if no more articles and not first page
      if (!hasMore && page > 1) return;

      const isFirstPage = page === 1;
      if (isFirstPage) setLoading(true);
      else setIsFetchingMore(true);

      const TIMEFRAME_DAYS = {
        '1d': 1,
        '7d': 7,
        '30d': 30,
        '1y': 365
      };

      const days = TIMEFRAME_DAYS[activeTab];
      const limit = 20;
      const offset = (page - 1) * limit;

      // Filter by timeframe
      const cutoff = new Date();
      cutoff.setDate(cutoff.getDate() - days);

      const filteredArticles = allData.articles.filter(article => {
        const pubDate = new Date(article.published);
        return pubDate > cutoff;
      });

      // Slice for pagination
      const pagedArticles = filteredArticles.slice(offset, offset + limit);

      if (pagedArticles.length < limit || offset + limit >= filteredArticles.length) {
        setHasMore(false);
      }

      setArticles(prev => {
        if (isFirstPage) return pagedArticles;
        // Ensure no duplicates
        const existingIds = new Set(prev.map(a => a.id));
        const uniqueNew = pagedArticles.filter(a => !existingIds.has(a.id));
        return [...prev, ...uniqueNew];
      });

      // Handle Trend Summaries
      if ((activeTab === '30d' || activeTab === '1y') && isFirstPage) {
        const summaryData = allData.summaries[activeTab];
        if (summaryData && summaryData.summary) {
          try {
            const parsed = JSON.parse(summaryData.summary);
            setTrendSummary({ ...summaryData, parsed });
          } catch (e) {
            console.error("Failed to parse trend summary JSON", e);
          }
        }
      }

      setLoading(false);
      setIsFetchingMore(false);
    }

    // Small delay to simulate network/smooth loading if needed, but here we just run it
    filterAndPaginate();
  }, [allData, activeTab, page]);

  const loadMore = () => {
    if (!loading && !isFetchingMore && hasMore) {
      setPage(prev => prev + 1);
    }
  };

  return (
    <div className="min-h-screen bg-cream selection:bg-black selection:text-white">
      <div className="max-w-3xl mx-auto px-6 py-12 md:py-20">

        {/* Header */}
        <header className="mb-12">
          <h1 className="text-4xl md:text-5xl font-serif font-bold text-text-main mb-2 tracking-tight">
            AI News
          </h1>
          <h2 className="text-xl font-serif text-gray-600 italic mb-4">
            Summarised by Abdi Timer and his AI Team
          </h2>
          <p className="text-gray-400 font-sans text-sm uppercase tracking-widest">
            Curated updates from the frontier of intelligence.
          </p>
        </header>

        {/* Navigation */}
        <TimeframeSelector activeTab={activeTab} onTabChange={setActiveTab} />

        {/* Content */}
        <main>
          {/* Trend Chips (Interactive) */}
          {trendSummary && trendSummary.parsed && (
            <div className="mb-12">
              <div className="flex items-center gap-2 mb-4">
                <span className="text-xs font-bold text-openai uppercase tracking-widest">Trend Analysis</span>
                <span className="text-xs text-gray-400">Filter by major themes</span>
              </div>

              <div className="flex flex-wrap gap-4">
                <button
                  onClick={() => setSelectedTrend(null)}
                  className={`text-left p-4 rounded-lg border transition-all duration-200 flex-1 min-w-[200px] ${!selectedTrend
                    ? 'bg-black text-white border-black shadow-lg ring-1 ring-black'
                    : 'bg-white text-gray-500 border-gray-100 hover:border-gray-300'
                    }`}
                >
                  <h3 className="font-bold text-sm mb-1">All Trends</h3>
                  <p className="text-xs opacity-80">Show all {articles.length} articles</p>
                </button>

                {trendSummary.parsed.trends?.map((trend, idx) => (
                  <button
                    key={idx}
                    onClick={() => setSelectedTrend(trend)}
                    className={`text-left p-4 rounded-lg border transition-all duration-200 flex-1 min-w-[200px] ${selectedTrend === trend
                      ? 'bg-black text-white border-black shadow-lg ring-1 ring-black'
                      : 'bg-white text-gray-600 border-gray-100 hover:border-gray-300'
                      }`}
                  >
                    <h3 className="font-bold text-sm mb-1">{trend.name}</h3>
                    <p className="text-xs opacity-80 line-clamp-2">{trend.summary}</p>
                  </button>
                ))}
              </div>
            </div>
          )}

          <div className="mb-8">
            <h2 className="text-sm font-sans font-bold text-gray-400 uppercase tracking-widest mb-6">
              Latest Articles
            </h2>
            <ArticleStream
              articles={articles}
              loading={loading}
              selectedTrend={selectedTrend}
              loadMore={loadMore}
              hasMore={hasMore}
            />
          </div>
        </main>

        <footer className="mt-20 pt-8 border-t border-gray-200 text-center text-gray-400 text-sm font-sans">
          <p>© {new Date().getFullYear()} AI News Summarised by Abdi Timer and his AI Team. All Rights Reserved.</p>
        </footer>

      </div>
    </div>
  );
}

export default App;
